name: Publish Docker Image

on:
  # Trigger on push
  push:
  # Trigger on all pull requests
  pull_request:
  # Trigger when a release is published
  release:
    types: ['published']

jobs:
  publish-container-image:
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
    uses: datum-cloud/actions/.github/workflows/publish-docker.yaml@v1.8.1
    with:
      image-name: galactic-agent
      platforms: "linux/amd64,linux/arm64"
    secrets: inherit

  publish-kustomize-bundles:
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: datum-cloud/actions/.github/workflows/publish-kustomize-bundle.yaml@v1.6.5
    with:
      bundle-name: ghcr.io/datum-cloud/galactic-agent-kustomize
      bundle-path: config
    secrets: inherit
